/*
 * auto-generated by script, DO NOT modify this file manually
 */
export namespace ItemTableTemplate {

    export interface IItemTableData {
        itemId: number,
        itemName: string,
        itemType: number,
        itemDesic?: string,
        maxNuminunit?: number,
        maxnumHold?: number,
        iconPath?: string[],
    };

    let _size: number | null = null;

    let _datas: { [key: number]: IItemTableData } = {
        10001: {
            itemId: 10001,
            itemName: '铜币',
            itemType: 1,
            itemDesic: '游戏中的通用货币；',
        },
        20001: {
            itemId: 20001,
            itemName: '勾玉',
            itemType: 2,
            itemDesic: '游戏中的通用货币；',
        },
        30001: {
            itemId: 30001,
            itemName: '金币',
            itemType: 3,
            itemDesic: '俱乐部中的通用货币；',
        },
        40001: {
            itemId: 40001,
            itemName: '温馨小屋',
            itemType: 4,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['common_bg_hall'],
        },
        50001: {
            itemId: 50001,
            itemName: '默认立直棒',
            itemType: 5,
            maxNuminunit: 1,
            maxnumHold: 1,
        },
        60001: {
            itemId: 60001,
            itemName: '默认桌布',
            itemType: 6,
            maxNuminunit: 1,
            maxnumHold: 1,
        },
        70001: {
            itemId: 70001,
            itemName: '默认牌背',
            itemType: 7,
            maxNuminunit: 1,
            maxnumHold: 1,
        },
        80001: {
            itemId: 80001,
            itemName: '紗也佳',
            itemType: 8,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['gamehall_maincharacter'],
        },
        130001: {
            itemId: 130001,
            itemName: '头像1',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n1'],
        },
        130002: {
            itemId: 130002,
            itemName: '头像2',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n2'],
        },
        130003: {
            itemId: 130003,
            itemName: '头像3',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n3'],
        },
        130004: {
            itemId: 130004,
            itemName: '头像4',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n4'],
        },
        130005: {
            itemId: 130005,
            itemName: '头像5',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n5'],
        },
        130006: {
            itemId: 130006,
            itemName: '头像6',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n6'],
        },
        130007: {
            itemId: 130007,
            itemName: '头像7',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n7'],
        },
        130008: {
            itemId: 130008,
            itemName: '头像8',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n8'],
        },
        130009: {
            itemId: 130009,
            itemName: '头像9',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n9'],
        },
        130010: {
            itemId: 130010,
            itemName: '头像10',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n10'],
        },
        130011: {
            itemId: 130011,
            itemName: '头像11',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n11'],
        },
        130012: {
            itemId: 130012,
            itemName: '头像12',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n12'],
        },
        130013: {
            itemId: 130013,
            itemName: '头像13',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n13'],
        },
        130014: {
            itemId: 130014,
            itemName: '头像14',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n14'],
        },
        130015: {
            itemId: 130015,
            itemName: '头像15',
            itemType: 13,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['avatar_img_n15'],
        },
        100001: {
            itemId: 100001,
            itemName: '俱乐部图标1',
            itemType: 10,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['clubicon_img_n1'],
        },
        100002: {
            itemId: 100002,
            itemName: '俱乐部图标2',
            itemType: 10,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['clubicon_img_n2'],
        },
        100003: {
            itemId: 100003,
            itemName: '俱乐部图标3',
            itemType: 10,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['clubicon_img_n3'],
        },
        100004: {
            itemId: 100004,
            itemName: '俱乐部图标4',
            itemType: 10,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['clubicon_img_n4'],
        },
        100005: {
            itemId: 100005,
            itemName: '俱乐部图标5',
            itemType: 10,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['clubicon_img_n5'],
        },
        100006: {
            itemId: 100006,
            itemName: '俱乐部图标6',
            itemType: 10,
            maxNuminunit: 1,
            maxnumHold: 1,
            iconPath: ['clubicon_img_n6'],
        },
    };

    /**
     * 查询
     * @param itemIdKey 数据项的 key
     * @returns 只读的数据项（可能为空）
     */
    export function query(itemIdKey: number): Readonly<IItemTableData> | null {
        return _datas[itemIdKey] ?? null;
    }

    /**
     * 获取数据项列表
     * @returns 只读的数据项列表
     */
    export function datas(): Readonly<{ [key: number]: Readonly<IItemTableData> }> {
        return _datas;
    }

    /**
     * 获取数据项数量
     * @returns 数据项数量
     */
    export function size(): number {
        if (!_size) {
            _size = 0;
            for (const _ in _datas) {
                ++_size;
            }
        }
        return _size;
    }

}
