/*
 * auto-generated by script, DO NOT modify this file manually
 */
export namespace ProductTableTemplate {

    export interface IProductTableData {
        productId: number,
        productName: string,
        googlestoreId?: string,
        appstoreId?: string,
        consumeditemId?: number,
        consumeditemNum?: number,
        rewardsId: number,
        rewardsNum: number,
        productPrice: number,
        shopType: number,
        shopPlace: number,
        productImg: string,
    };

    let _size: number | null = null;

    let _datas: { [key: number]: IProductTableData } = {
        501: {
            productId: 501,
            productName: '50金币',
            rewardsId: 30001,
            rewardsNum: 50,
            productPrice: 5000,
            shopType: 5,
            shopPlace: 1,
            productImg: 'store_icn_jade_03',
        },
        502: {
            productId: 502,
            productName: '100金币',
            rewardsId: 30001,
            rewardsNum: 100,
            productPrice: 10000,
            shopType: 5,
            shopPlace: 2,
            productImg: 'store_icn_jade_04',
        },
        503: {
            productId: 503,
            productName: '200金币',
            rewardsId: 30001,
            rewardsNum: 200,
            productPrice: 20000,
            shopType: 5,
            shopPlace: 3,
            productImg: 'store_icn_jade_05',
        },
        504: {
            productId: 504,
            productName: '500金币',
            rewardsId: 30001,
            rewardsNum: 500,
            productPrice: 50000,
            shopType: 5,
            shopPlace: 4,
            productImg: 'store_icn_jade_06',
        },
        505: {
            productId: 505,
            productName: '1000金币',
            rewardsId: 30001,
            rewardsNum: 1000,
            productPrice: 100000,
            shopType: 5,
            shopPlace: 5,
            productImg: 'store_icn_jade_07',
        },
        506: {
            productId: 506,
            productName: '2000金币',
            rewardsId: 30001,
            rewardsNum: 2000,
            productPrice: 200000,
            shopType: 5,
            shopPlace: 6,
            productImg: 'store_icn_jade_08',
        },
        101: {
            productId: 101,
            productName: '5千铜币',
            consumeditemId: 20001,
            consumeditemNum: 10,
            rewardsId: 10001,
            rewardsNum: 5000,
            productPrice: 0,
            shopType: 1,
            shopPlace: 1,
            productImg: 'store_icn_coin_2',
        },
        102: {
            productId: 102,
            productName: '3万铜币',
            consumeditemId: 20001,
            consumeditemNum: 60,
            rewardsId: 10001,
            rewardsNum: 30000,
            productPrice: 0,
            shopType: 1,
            shopPlace: 2,
            productImg: 'store_icn_coin_3',
        },
        103: {
            productId: 103,
            productName: '6万铜币',
            consumeditemId: 20001,
            consumeditemNum: 120,
            rewardsId: 10001,
            rewardsNum: 60000,
            productPrice: 0,
            shopType: 1,
            shopPlace: 3,
            productImg: 'store_icn_coin_4',
        },
        104: {
            productId: 104,
            productName: '15万铜币',
            consumeditemId: 20001,
            consumeditemNum: 300,
            rewardsId: 10001,
            rewardsNum: 150000,
            productPrice: 0,
            shopType: 1,
            shopPlace: 4,
            productImg: 'store_icn_coin_5',
        },
        105: {
            productId: 105,
            productName: '30万铜币',
            consumeditemId: 20001,
            consumeditemNum: 600,
            rewardsId: 10001,
            rewardsNum: 300000,
            productPrice: 0,
            shopType: 1,
            shopPlace: 5,
            productImg: 'store_icn_coin_6',
        },
        106: {
            productId: 106,
            productName: '52万铜币',
            consumeditemId: 20001,
            consumeditemNum: 1000,
            rewardsId: 10001,
            rewardsNum: 520000,
            productPrice: 0,
            shopType: 1,
            shopPlace: 6,
            productImg: 'store_icn_coin_7',
        },
        107: {
            productId: 107,
            productName: '110万铜币',
            consumeditemId: 20001,
            consumeditemNum: 2000,
            rewardsId: 10001,
            rewardsNum: 1100000,
            productPrice: 0,
            shopType: 1,
            shopPlace: 7,
            productImg: 'store_icn_coin_8',
        },
        201: {
            productId: 201,
            productName: '60勾玉',
            appstoreId: 'com.radicalkoi.mahjong.magatama.level1',
            rewardsId: 20001,
            rewardsNum: 60,
            productPrice: 600,
            shopType: 2,
            shopPlace: 1,
            productImg: 'store_icn_magatama_2',
        },
        202: {
            productId: 202,
            productName: '300勾玉',
            appstoreId: 'com.radicalkoi.mahjong.magatama.level02',
            rewardsId: 20001,
            rewardsNum: 300,
            productPrice: 3000,
            shopType: 2,
            shopPlace: 2,
            productImg: 'store_icn_magatama_3',
        },
        203: {
            productId: 203,
            productName: '980勾玉',
            appstoreId: 'com.radicalkoi.mahjong.magatama.level3',
            rewardsId: 20001,
            rewardsNum: 980,
            productPrice: 9800,
            shopType: 2,
            shopPlace: 3,
            productImg: 'store_icn_magatama_4',
        },
        204: {
            productId: 204,
            productName: '1980勾玉',
            appstoreId: 'com.radicalkoi.mahjong.magatama.level4',
            rewardsId: 20001,
            rewardsNum: 1980,
            productPrice: 19800,
            shopType: 2,
            shopPlace: 4,
            productImg: 'store_icn_magatama_5',
        },
        205: {
            productId: 205,
            productName: '3280勾玉',
            appstoreId: 'com.radicalkoi.mahjong.magatama.level5',
            rewardsId: 20001,
            rewardsNum: 3280,
            productPrice: 32800,
            shopType: 2,
            shopPlace: 5,
            productImg: 'store_icn_magatama_6',
        },
        206: {
            productId: 206,
            productName: '6480勾玉',
            appstoreId: 'com.radicalkoi.mahjong.magatama.level6',
            rewardsId: 20001,
            rewardsNum: 6480,
            productPrice: 64800,
            shopType: 2,
            shopPlace: 6,
            productImg: 'store_icn_magatama_7',
        },
    };

    /**
     * 查询
     * @param productIdKey 数据项的 key
     * @returns 只读的数据项（可能为空）
     */
    export function query(productIdKey: number): Readonly<IProductTableData> | null {
        return _datas[productIdKey] ?? null;
    }

    /**
     * 获取数据项列表
     * @returns 只读的数据项列表
     */
    export function datas(): Readonly<{ [key: number]: Readonly<IProductTableData> }> {
        return _datas;
    }

    /**
     * 获取数据项数量
     * @returns 数据项数量
     */
    export function size(): number {
        if (!_size) {
            _size = 0;
            for (const _ in _datas) {
                ++_size;
            }
        }
        return _size;
    }

}
